### ISSUE TITLE
Repository Over Data Quota

### ISSUE THREAD

**Issue by forrestrice** [DevinTDHa/precompiled-tf-jni-m1#2]
Thanks for doing this work. Unfortunately I cannot access the jars from git lfs - I get the following error:
```
% git lfs pull         
batch response: This repository is over its data quota. Account responsible for LFS bandwidth should purchase more data packs to restore access.                                                                                                                            
Failed to fetch some objects from 'https://github.com/DevinTDHa/precompiled-tf-jni-m1.git/info/lfs'
```

Depending on the cost I may be able to contribute something.

**Comment by DevinTDHa** [comment]
Hi,
sorry for the late reply. I have created a release for the files here:

https://github.com/DevinTDHa/precompiled-tf-jni-m1/releases

This way, the files can be downloaded by everyone, instead of needing it to checkout with gitlfs.
